Improve test coverage
sokil/php-vast pull request #22
Opened 2018-10-30 15:20 UTC by dorantor

During adding new tests and looking for a better way improve coverage, found issue here:
https://coveralls.io/builds/19781394/source?filename=src/Document.php#L181

Last commit tries to improve this `not so well thought code` that I sent initially. But! Currently it creates a possible problem, because it changes interface for `constructor()`  for `AbstractAdNode`. 
But the way I did it now seems to be a proper or at least better one. And this should not be an issue, because descendants of this class should always be created via "factories" in other classes.

So I decided to send an incomplete PR. While waiting for feedback will keep working on improving coverage further :)

2018-10-30 20:58 UTC, dorantor commented
Hehe. It's 100% now :) 
But please check https://github.com/sokil/php-vast/pull/22/commits/06b6535c8249983c96f3617846dc968bc8315273 before merging. You might want me to bring back original API.

2018-11-06 22:18 UTC, sokil requested changes

2018-11-06 22:18 UTC, sokil commented on tests/DocumentTest.php
> +        $adParams->setParams(array(
i'v fix this and `adParameterds` now set throug setter, because `adParameters` is single node and can't be created twice

2018-11-06 22:18 UTC, sokil commented on src/Document.php
> +        return $this->createAdSection($this->createAdSectionDomEl('InLine'));
1) argument not used
2) DomDocument must be completely hidden from library interface. Goal of this library is to hide complexity of xml manipulations by explicit interface able to autocomplete. If you publis internal imprementation, you never change DomDocument to something else.

2018-11-06 22:18 UTC, sokil commented on src/Document.php
> +    private function createAdSectionDomEl($type)
Why you extract this method. This code may be in `createAdSection`

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +            $this->loadCreativesFromDom();
no reason to extract this to method

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +        $this->adDomElement = $domElement->parentNode;
why you change this?

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +            $this->creativesDomElement = $this->adDomElement->getElementsByTagName('Creatives')->item(0);
`creativesDomElement ` already build in `buildCreative`. This is getter but you add side effect of creating Creatives tag. If you load xml, tried to get creatives, your dom will change.  And also this is copy paste of `Creatives` tag creation.

If `creativesDomElement ` empty, just do nothing.

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +                continue; // skip empty <Creative/>
why you skip it? you may want to set something to it.

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +            $el = new \DOMText();
why you set iot to \DOMText() and not just to null?

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> -        $parts = explode('\\', get_class($this));
Where is this method?

2018-11-06 22:18 UTC, sokil commented on src/Ad/AbstractAdNode.php
> +            $this->creatives[] = $creative;
```php
$ad->createLinearCreative();
$ad->getCreatives()
```

// now you have two creative instances in `$this->creatives`. Please, add test with this case.

2018-11-06 22:18 UTC, sokil commented on src/Creative/AbstractLinearCreative.php
> +     * @return array
string[]

2018-11-06 22:18 UTC, sokil commented on src/Creative/AbstractLinearCreative.php
> +     * @return array
string[]

2018-11-06 22:18 UTC, sokil commented on src/Creative/AbstractLinearCreative.php
> +     * @return array
string[][]

2018-11-06 22:18 UTC, sokil commented on src/Document.php
> +                throw new \Exception('Ad type ' . $domEl->tagName . ' not supported');
library must throw own exception. Maybe better to implement `\Sokil\Vast\Exception` and throw it? And i think we need to move in v.2.0 to some other vendor name ))))

2018-11-06 22:18 UTC, sokil commented on src/Document.php
> +            $this->createAdSectionDomEl('Wrapper')
createAdSectionDomEl<ement>. Code must be readable ) IDE will help to autocomplete long names

2018-11-06 22:18 UTC, sokil commented on tests/DocumentTest.php
> +        self::assertInstanceOf('Sokil\Vast\Document', $document);
$factory->fromFile can not return nothing else

2018-11-06 22:18 UTC, sokil commented on tests/DocumentTest.php
> +        // test with multiurls and w/o attribute
w/o?

2018-11-06 22:18 UTC, sokil commented on tests/DocumentTest.php
> +        self::assertEquals(
this tests test to much in one method. If test will fail, it will be difficult to understand where problem is. test must test one thing.

2018-11-06 22:18 UTC, sokil commented on tests/DocumentTest.php
> +        $method->setAccessible(true);
bad idea. Reflection broke incapsulation. If you can call getScalarNodeValue with invalid name in some public method, test this public method. If no such method  - its nothing to test. I think its just for 100% coverage ))))

Coverage do not mean that your code 100% valid. It means that you call 100% of lines in your test, and nothing more. You can write test that call anything and do no assertions and your coverage will be 100% but code not tested.

2018-11-06 22:18 UTC, sokil commented on tests/data/vastTrackingEvents.xml
> +    <Ad id="ad0">
maybe better to create little vast files to test one thing?

2019-01-29 09:00 UTC, dorantor commented
I'm currently too much busy at work. And it seems that I will be able to continue with fixes only after two months. So, I think, it would be easier to close this PR and next time I'll just make a new one. WDYT?

2019-01-29 09:13 UTC, sokil commented
See no problems with opened pull requests ) do what you consider necessary

2019-09-26 19:11 UTC, closed without merging